import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BrowserRouter, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { canQuickComplete, createCourseTaskDraft, dateKey, getDashboardGroups, getMonthCells, groupTasksByType, isTaskOverdue, matchesTask } from "./domain/tasks";
import { courseSlots, coursesForTeachingWeek, getTeachingWeek, hasActiveCourseOnDate, parseRoutineImport, parseScheduleImport, parseWeekSelection, routineAiPrompt, routineTemplate, scheduleTemplate } from "./domain/courses";
import { hasIeltsCourseOnDate, ieltsCourseNamesOnDate } from "./domain/ielts";
import { courseApi } from "./services/courseApi";
import { taskApi } from "./services/taskApi";
import { ieltsApi } from "./services/ieltsApi";
import type { Course, CourseInput, CourseUpdateInput, Schedule, ScheduleImportInput, ScheduleSettings, ScheduleUpdateInput } from "./types/course";
import type { IeltsCourse } from "./types/ielts";
import type { Task, TaskFilters, TaskInput, TaskPriority, TaskStatus, TaskType } from "./types/task";
import IeltsPage from "./IeltsPage";
import "./App.css";
import "./Course.css";

const typeLabels: Record<TaskType, string> = { ielts: "雅思", competition: "竞赛", course: "课程", other: "其他" };
const priorityLabels: Record<TaskPriority, string> = { low: "低", medium: "中", high: "高", urgent: "紧急" };
const statusLabels: Record<TaskStatus, string> = { not_started: "未开始", completed: "已完成", incomplete: "未完成", cancelled: "已取消" };
const courseTaskLabels: Record<string, string> = { assignment: "作业", test: "测试", exam: "考试", report: "报告", other: "其他" };

function formatDateTime(value: string | null) {
  if (!value) return "未设置时间";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value.replace("T", " ");
  return new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(date);
}

function Icon({ name }: { name: "home" | "tasks" | "calendar" | "course" | "plus" }) {
  const paths = {
    home: <><path d="M3 11.5 12 4l9 7.5"/><path d="M5 10.5V20h14v-9.5M9 20v-6h6v6"/></>,
    tasks: <><path d="M9 6h11M9 12h11M9 18h11"/><path d="m3.5 6 1 1 2-2M3.5 12l1 1 2-2M3.5 18l1 1 2-2"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    course: <><path d="M4 5h16v14H4zM8 3v4M16 3v4M4 9h16"/><path d="M8 13h3M13 13h3M8 16h3"/></>,
    plus: <path d="M12 5v14M5 12h14"/>,
  };
  return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">{paths[name]}</svg>;
}

function EmptyState({ text, onAdd }: { text: string; onAdd: () => void }) {
  return <div className="empty"><div className="empty-mark">✓</div><p>{text}</p><button className="text-button" onClick={onAdd}>新增一项</button></div>;
}

function TaskRow({ task, onEdit, onStatus }: { task: Task; onEdit: (task: Task) => void; onStatus: (task: Task, status: TaskStatus) => void }) {
  const overdue = isTaskOverdue(task);
  return <article className={`task-row ${task.status === "completed" ? "is-complete" : ""}`}>
    {canQuickComplete(task.taskType) && <button className="check" aria-label={task.status === "completed" ? "设为未开始" : "完成任务"} onClick={() => onStatus(task, task.status === "completed" ? "not_started" : "completed")}>{task.status === "completed" ? "✓" : ""}</button>}
    <button className="task-main" onClick={() => onEdit(task)}><span className="task-title">{task.title}</span><span className="task-meta"><i className={`type-dot type-${task.taskType}`} />{typeLabels[task.taskType]}{task.courseTaskType ? ` · ${task.customCourseTaskType || courseTaskLabels[task.courseTaskType]}` : ""} · <span className={overdue ? "overdue" : ""}>{overdue ? "已逾期 · " : ""}{formatDateTime(task.dueAt)}</span></span></button>
    {task.taskType !== "course" && <span className={`priority priority-${task.priority}`}>{priorityLabels[task.priority]}</span>}
  </article>;
}

interface PageProps { tasks: Task[]; courses?: Course[]; schedules?: Schedule[]; ieltsCourses?: IeltsCourse[]; ieltsWorkCount?: number; semesterStartDate?: string; onAdd: (dueAt?: string) => void; onEdit: (task: Task) => void; onStatus: (task: Task, status: TaskStatus) => void }

function Dashboard(props: PageProps) {
  const navigate = useNavigate();
  const groups = useMemo(() => getDashboardGroups(props.tasks), [props.tasks]);
  const unscheduled = props.tasks.filter((task) => !task.dueAt && (task.status === "not_started" || task.status === "incomplete"));
  const pending = props.tasks.filter((task) => task.status === "not_started" || task.status === "incomplete").length;
  const completed = props.tasks.filter((task) => task.status === "completed").length;
  return <div className="page">
    <header className="page-header hero"><div><p className="eyebrow">今天也向前一步</p><h1>你好，欢迎回来</h1><p>这里是你近期规划的全貌。</p></div><button className="primary" onClick={() => props.onAdd()}><Icon name="plus" />新增任务</button></header>
    <section className="local-data-overview" aria-label="已加载的本地内容">
      <button onClick={() => navigate("/tasks")}><span>本地任务</span><strong>{props.tasks.length}</strong><small>查看全部任务</small></button>
      <button onClick={() => navigate("/courses")}><span>课表课程</span><strong>{props.courses?.length ?? 0}</strong><small>查看课程与课表</small></button>
      <button onClick={() => navigate("/ielts/courses")}><span>雅思课程</span><strong>{props.ieltsCourses?.length ?? 0}</strong><small>查看已导入课程</small></button>
      <button onClick={() => navigate("/ielts/homework")}><span>雅思作业</span><strong>{props.ieltsWorkCount ?? 0}</strong><small>查看作业与自测</small></button>
    </section>
    {unscheduled.length > 0 && <section className="panel saved-tasks"><div className="panel-title"><div><span className="section-kicker">SAVED TASKS</span><h2>未设置时间的任务</h2></div><button className="text-button" onClick={() => navigate("/tasks")}>查看全部</button></div>{unscheduled.slice(0, 5).map((task) => <TaskRow key={task.recordId} task={task} onEdit={props.onEdit} onStatus={props.onStatus} />)}</section>}
    <section className="stats-grid"><div className="stat"><span>待完成</span><strong>{pending}</strong><small>所有进行中的任务</small></div><div className="stat accent"><span>今天</span><strong>{groups.today.length}</strong><small>需要在今天处理</small></div><div className="stat warning"><span>已逾期</span><strong>{groups.overdue.length}</strong><small>建议优先安排</small></div><div className="stat success"><span>已完成</span><strong>{completed}</strong><small>继续保持节奏</small></div></section>
    <div className="dashboard-grid">
      <section className="panel"><div className="panel-title"><div><span className="section-kicker">TODAY</span><h2>今日任务</h2></div><button className="text-button" onClick={() => navigate("/tasks")}>查看全部</button></div>{groups.today.length ? groups.today.map((task) => <TaskRow key={task.recordId} task={task} onEdit={props.onEdit} onStatus={props.onStatus} />) : <EmptyState text="今天还没有安排" onAdd={() => props.onAdd(`${dateKey(new Date())}T18:00`)} />}</section>
      <section className="panel"><div className="panel-title"><div><span className="section-kicker">NEXT 7 DAYS</span><h2>未来 7 天</h2></div></div>{groups.upcoming.length ? groups.upcoming.slice(0, 5).map((task) => <TaskRow key={task.recordId} task={task} onEdit={props.onEdit} onStatus={props.onStatus} />) : <EmptyState text="未来一周很从容" onAdd={() => props.onAdd()} />}</section>
    </div>
  </div>;
}

function TasksPage(props: PageProps) {
  const [filters, setFilters] = useState<TaskFilters>({ query: "", type: "all", status: "all" });
  const filtered = props.tasks.filter((task) => matchesTask(task, filters));
  const grouped = groupTasksByType(filtered);
  return <div className="page"><header className="page-header"><div><p className="eyebrow">TASKS</p><h1>全部任务</h1><p>集中管理每一件需要推进的事。</p></div><button className="primary" onClick={() => props.onAdd()}><Icon name="plus" />新增任务</button></header>
    <section className="panel filters"><input className="search" placeholder="搜索任务、描述或标签…" value={filters.query} onChange={(event) => setFilters({ ...filters, query: event.target.value })} /><select value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value as TaskFilters["type"] })}><option value="all">全部类型</option>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value as TaskFilters["status"] })}><option value="all">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></section>
    <div className="grouped-tasks">{filtered.length ? (["ielts","competition","course","other"] as TaskType[]).map((type) => grouped[type].length > 0 && <section className="panel task-list" key={type}><div className="task-group-title"><i className={`type-dot type-${type}`}/><strong>{typeLabels[type]}</strong><span>{grouped[type].length} 项</span></div>{grouped[type].map((task) => <TaskRow key={task.recordId} task={task} onEdit={props.onEdit} onStatus={props.onStatus} />)}</section>) : <section className="panel"><EmptyState text="没有找到符合条件的任务" onAdd={() => props.onAdd()} /></section>}</div></div>;
}

function CalendarPage(props: PageProps) {
  const [cursor, setCursor] = useState(() => new Date());
  const [visibleScheduleIds, setVisibleScheduleIds] = useState<string[]>([]);
  const schedules = props.schedules ?? [];
  useEffect(() => { if (!visibleScheduleIds.length && schedules.length) setVisibleScheduleIds(schedules.map((schedule) => schedule.id)); }, [schedules, visibleScheduleIds.length]);
  const cells = getMonthCells(cursor.getFullYear(), cursor.getMonth(), props.tasks);
  const monthLabel = new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "long" }).format(cursor);
  const shiftMonth = (offset: number) => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + offset, 1));
  return <div className="page"><header className="page-header"><div><p className="eyebrow">CALENDAR</p><h1>日历</h1><p>按时间查看任务，点击日期即可新增。</p></div><button className="primary" onClick={() => props.onAdd()}><Icon name="plus" />新增任务</button></header>
    <section className="panel calendar-panel"><div className="calendar-toolbar"><button className="round" onClick={() => shiftMonth(-1)}>‹</button><h2>{monthLabel}</h2><button className="round" onClick={() => shiftMonth(1)}>›</button><button className="ghost today-button" onClick={() => setCursor(new Date())}>回到今天</button></div><div className="schedule-legend"><strong>课表：</strong><button className="ghost" onClick={() => setVisibleScheduleIds(schedules.map((schedule) => schedule.id))}>全部</button>{schedules.map((schedule) => <label key={schedule.id}><input type="checkbox" checked={visibleScheduleIds.includes(schedule.id)} onChange={() => setVisibleScheduleIds((ids) => ids.includes(schedule.id) ? ids.filter((id) => id !== schedule.id) : [...ids, schedule.id])}/><i style={{ background: schedule.color }}/>{schedule.name}</label>)}</div><div className="weekdays">{["周一", "周二", "周三", "周四", "周五", "周六", "周日"].map((day) => <span key={day}>{day}</span>)}</div>
      <div className="calendar-grid">{cells.map((cell) => { const activeSchedules = schedules.filter((schedule) => visibleScheduleIds.includes(schedule.id) && hasActiveCourseOnDate((cell.date), (props.courses ?? []).filter((course) => course.scheduleId === schedule.id), schedule.semesterStartDate)); const ieltsCourse = hasIeltsCourseOnDate(cell.date, props.ieltsCourses ?? []); const ieltsNames = ieltsCourseNamesOnDate(cell.date, props.ieltsCourses ?? []); return <div key={cell.dateKey} className={`calendar-cell ${cell.inMonth ? "" : "outside"} ${cell.dateKey === dateKey(new Date()) ? "today" : ""} ${activeSchedules.length ? "has-course" : ""} ${ieltsCourse ? "has-ielts-course" : ""}`}><div className="calendar-schedule-colors">{activeSchedules.map((schedule) => <i key={schedule.id} title={schedule.name} style={{ background: schedule.color }}/>)}</div><button className="day-number" onClick={() => props.onAdd(`${cell.dateKey}T18:00`)}>{cell.date.getDate()}</button>{ieltsNames.map(name=><span className="ielts-course-mark" key={name}>{name}</span>)}<div className="calendar-tasks">{cell.tasks.slice(0, 3).map((task) => <button key={task.recordId} className={`calendar-task type-bg-${task.taskType} ${task.status === "completed" ? "done" : ""}`} onClick={() => props.onEdit(task)} title={task.title}>{task.title}</button>)}{cell.tasks.length > 3 && <small>+{cell.tasks.length - 3} 项</small>}</div></div>; })}</div>
    </section></div>;
}

function CoursePage({ courses, schedules = [], tasks, onOpenImport, onDeleteSchedule, onAddAssignment, onEditTask, onSaveCourse, onSaveSchedule }: { courses: Course[]; schedules?: Schedule[]; tasks: Task[]; onOpenImport: () => void; onDeleteSchedule: (id: string) => Promise<void>; onAddAssignment: (courseId: string) => void; onEditTask: (task: Task) => void; onSaveCourse: (id: string, input: CourseUpdateInput) => Promise<void>; onSaveSchedule: (id: string, input: ScheduleUpdateInput) => Promise<void> }) {
  const weekdays = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"];
  const [range, setRange] = useState<"week" | "all">("week");
  const [selectedScheduleId, setSelectedScheduleId] = useState("");
  const [editing, setEditing] = useState<Course | null>(null), [scheduleEditing, setScheduleEditing] = useState(false), [routineEditing, setRoutineEditing] = useState(false), [editMode, setEditMode] = useState(false);
  const [pendingCourseUpdates, setPendingCourseUpdates] = useState<Array<{ id: string; input: CourseUpdateInput }>>([]), [savingEdits, setSavingEdits] = useState(false);
  const [moving, setMoving] = useState<{ course: Course; x: number; y: number } | null>(null), [resizing, setResizing] = useState<{ course: Course; edge: "top" | "bottom" } | null>(null);
  const [resizePreview, setResizePreview] = useState<Course | null>(null), [movePreview, setMovePreview] = useState<Course | null>(null);
  const gridRef = useRef<HTMLDivElement | null>(null), resizePreviewRef = useRef<Course | null>(null), movePreviewRef = useRef<Course | null>(null), movedRef = useRef(false);
  useEffect(() => { if (!selectedScheduleId && schedules[0]) setSelectedScheduleId(schedules[0].id); }, [schedules, selectedScheduleId]);
  const schedule = schedules.find((item) => item.id === selectedScheduleId) ?? schedules[0];
  const scheduleCourses = courses.filter((course) => course.scheduleId === schedule?.id);
  const courseTasks = tasks.filter((task) => task.courseId);
  const teachingWeek = getTeachingWeek(new Date(), schedule?.semesterStartDate ?? "");
  const stagedCourses = scheduleCourses.map((course) => { const update = pendingCourseUpdates.find((item) => item.id === course.recordId); return update ? { ...course, ...update.input } : course; });
  const visibleCourses = range === "week" ? coursesForTeachingWeek(stagedCourses, new Date(), schedule?.semesterStartDate ?? "") : stagedCourses;
  const preview = resizePreview ?? movePreview;
  const slots = courseSlots(preview ? visibleCourses.map((course) => course.recordId === preview.recordId ? preview : course) : visibleCourses);
  useEffect(() => { if (!resizing || !gridRef.current) return; const move = (event: PointerEvent) => { const box = gridRef.current!.getBoundingClientRect(); const section = Math.max(1, Math.min(12, Math.floor((event.clientY - box.top) / 42) + 1)); const course = resizing.course; const next = { ...course, startSection: resizing.edge === "top" ? Math.min(section, course.endSection) : course.startSection, endSection: resizing.edge === "bottom" ? Math.max(section, course.startSection) : course.endSection }; resizePreviewRef.current = next; setResizePreview(next); }; const up = () => { if (resizePreviewRef.current) setEditing(resizePreviewRef.current); setResizing(null); setResizePreview(null); resizePreviewRef.current = null; }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, [resizing]);
  const startResize = (event: React.PointerEvent, course: Course, edge: "top" | "bottom") => { event.preventDefault(); event.stopPropagation(); if (!editMode) return; resizePreviewRef.current = course; setResizePreview(course); setResizing({ course, edge }); };
  useEffect(() => { if (!moving || !gridRef.current) return; const move = (event: PointerEvent) => { if (Math.hypot(event.clientX - moving.x, event.clientY - moving.y) < 5) return; const box = gridRef.current!.getBoundingClientRect(), columnWidth = (box.width - 54) / 7; const weekday = Math.floor((event.clientX - box.left - 54) / columnWidth) + 1, startSection = Math.floor((event.clientY - box.top) / 42) + 1; if (weekday < 1 || weekday > 7 || startSection < 1 || startSection > 12) return; const length = moving.course.endSection - moving.course.startSection; const next = { ...moving.course, weekday, startSection, endSection: Math.min(12, startSection + length) }; movedRef.current = true; movePreviewRef.current = next; setMovePreview(next); }; const up = () => { if (movedRef.current && movePreviewRef.current) setEditing(movePreviewRef.current); setMoving(null); setMovePreview(null); movePreviewRef.current = null; window.setTimeout(() => { movedRef.current = false; }, 0); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, [moving]);
  const startMove = (event: React.PointerEvent, course: Course) => { if (!editMode || event.button !== 0) return; movedRef.current = false; setMoving({ course, x: event.clientX, y: event.clientY }); };
  const stageCourseUpdate = (id: string, input: CourseUpdateInput) => { setPendingCourseUpdates((updates) => [...updates.filter((update) => update.id !== id), { id, input }]); };
  const cancelEdits = () => { setPendingCourseUpdates([]); setEditing(null); setEditMode(false); };
  const saveEdits = async () => { setSavingEdits(true); try { for (const update of pendingCourseUpdates) await onSaveCourse(update.id, update.input); setPendingCourseUpdates([]); setEditMode(false); } finally { setSavingEdits(false); } };
  return <div className="page"><header className="page-header"><div><p className="eyebrow">COURSES</p><h1>课程与课表</h1><p>{editMode ? "修改模式：拖动课程调整时间，或拖动左上、右下圆点调整节次。修改会先保存在本页草稿中。" : "点击课程可新增该课程作业。"}</p></div><div className="header-actions"><button className="primary" onClick={onOpenImport}><Icon name="plus"/>导入课表</button></div></header><div className="schedule-controls"><div className="range-switch"><button className={range === "week" ? "active" : ""} onClick={() => setRange("week")}>本周课程</button><button className={range === "all" ? "active" : ""} onClick={() => setRange("all")}>全部课程</button></div><div className="start-date-control"><label>选择课表<select value={schedule?.id ?? ""} onChange={(event) => setSelectedScheduleId(event.target.value)}>{schedules.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{schedule && <><i className="schedule-color-dot" style={{ background: schedule.color }}/><span>开学：{schedule.semesterStartDate} · {teachingWeek ? `当前第 ${teachingWeek} 周` : "尚未开学"}</span><button className="ghost" onClick={() => setScheduleEditing(true)}>课表设置</button><button className="ghost" onClick={() => setRoutineEditing(true)}>作息{schedule.routines.length ? "（已设置）" : "（未设置）"}</button>{schedules.length > 1 && <button className="ghost" onClick={() => { if (window.confirm(`删除课表“${schedule.name}”及其中课程？`)) void onDeleteSchedule(schedule.id); }}>删除课表</button>}</>}</div></div>
    {scheduleCourses.length === 0 ? <section className="panel schedule-empty"><div className="schedule-illustration">课</div><h2>这份课表还没有课程</h2><p>可新增一份课表，或在导入时选择覆盖当前课表。</p><button className="primary" onClick={onOpenImport}>开始导入课表</button></section> : <>
      <section className="panel schedule-panel"><div className="schedule-head"><span>节次</span>{weekdays.map((day) => <strong key={day}>{day}</strong>)}</div><div className={`week-grid ${editMode ? "schedule-editing" : ""}`} ref={gridRef}>{Array.from({ length: 12 }, (_, index) => <div className="section-label" style={{ gridRow: index + 1 }} key={index}><b>{index + 1}</b>{schedule?.routines.find((item) => item.section === index + 1) && <small>{schedule.routines.find((item) => item.section === index + 1)?.startTime}<br/>{schedule.routines.find((item) => item.section === index + 1)?.endTime}</small>}</div>)}{weekdays.map((_, day) => Array.from({ length: 12 }, (__, row) => <div className="schedule-slot" data-weekday={day + 1} data-section={row + 1} style={{ gridColumn: day + 2, gridRow: row + 1 }} key={`${day}-${row}`}/>))}{slots.map((slot) => <div className="course-slot-group" style={{ gridColumn: slot.weekday + 1, gridRow: `${slot.startSection} / ${slot.endSection + 1}` }} key={`${slot.weekday}-${slot.startSection}-${slot.endSection}`}>{slot.items.map(({ course, weekRanges }) => <div key={course.recordId} className="course-card" style={{ backgroundColor: `${course.color}22`, borderLeftColor: course.color }} onPointerDown={(event) => startMove(event, course)} onClick={() => { if (movedRef.current) return; editMode ? setEditing(course) : onAddAssignment(course.recordId); }} title={editMode ? "按住并移动可调整时间；点击编辑" : "点击新增这门课的作业"}>{editMode && <button className="resize-dot top" onPointerDown={(event) => startResize(event, course, "top")} aria-label="拖动调整开始节次"/>}<strong>{course.name}</strong><span>{course.classroom || "教室未填"}</span><small>第 {weekRanges.join("、")} 周</small>{editMode && <button className="resize-dot bottom" onPointerDown={(event) => startResize(event, course, "bottom")} aria-label="拖动调整结束节次"/>}</div>)}</div>)}</div>{range === "week" && visibleCourses.length === 0 && <p className="inline-empty">{schedule ? "本教学周没有课程。" : "请先导入一份课表。"}</p>}</section>
      <div className="schedule-edit-actions">{editMode ? <><span>{pendingCourseUpdates.length ? `已暂存 ${pendingCourseUpdates.length} 处修改` : "可拖动或点击课程开始修改"}</span><button className="ghost" disabled={savingEdits} onClick={cancelEdits}>取消并恢复</button><button className="primary" disabled={savingEdits || !pendingCourseUpdates.length} onClick={() => void saveEdits()}>{savingEdits ? "保存中…" : "保存修改"}</button></> : <button className="ghost" onClick={() => setEditMode(true)}>修改课表</button>}</div>
      <section className="panel course-assignments"><div className="panel-title"><div><span className="section-kicker">ASSIGNMENTS</span><h2>课程作业</h2></div></div>{courseTasks.length ? courseTasks.map((task) => { const course = courses.find((item) => item.recordId === task.courseId); return <button className="assignment-row" key={task.recordId} onClick={() => onEditTask(task)}><span className="course-chip" style={{ background: course?.color }}>{course?.name ?? "未知课程"}</span><strong>{task.title}</strong><span>{formatDateTime(task.dueAt)}</span></button>; }) : <p className="inline-empty">点击上方课表中的课程，即可为它添加作业。</p>}</section>
    </>}
  {editing && <CourseEditDialog course={editing} onClose={() => setEditing(null)} onSave={(input) => { stageCourseUpdate(editing.recordId, input); setEditing(null); }}/>} {schedule && scheduleEditing && <ScheduleEditDialog schedule={schedule} onClose={() => setScheduleEditing(false)} onSave={async (input) => { await onSaveSchedule(schedule.id, input); setScheduleEditing(false); }}/>} {schedule && routineEditing && <RoutineDialog schedule={schedule} onClose={() => setRoutineEditing(false)} onSave={async (input) => { await onSaveSchedule(schedule.id, input); setRoutineEditing(false); }}/>}</div>;
}

function CourseEditDialog({ course, onClose, onSave }: { course: Course; onClose: () => void; onSave: (input: CourseUpdateInput) => void }) {
  const [form, setForm] = useState<CourseInput>(() => ({ name: course.name, teacher: course.teacher, classroom: course.classroom, weekday: course.weekday, startSection: course.startSection, endSection: course.endSection, startTime: course.startTime, endTime: course.endTime, startWeek: course.startWeek, endWeek: course.endWeek, color: course.color }));
  const [scope, setScope] = useState<"all" | "some">("all"), [weeks, setWeeks] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const set = <K extends keyof CourseInput>(key: K, value: CourseInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); try { const scopeWeeks = scope === "some" ? parseWeekSelection(weeks, course.startWeek, course.endWeek) : undefined; setSaving(true); onSave({ ...form, scopeWeeks }); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setSaving(false); } };
  return <div className="modal-backdrop"><div className="modal"><form onSubmit={submit}><div className="modal-header"><div><span className="section-kicker">EDIT COURSE</span><h2>修改课程</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><div className="form-grid"><label className="field full"><span>课程名称 *</span><input autoFocus maxLength={120} value={form.name} onChange={(event) => set("name", event.target.value)}/></label><label className="field"><span>老师</span><input value={form.teacher} onChange={(event) => set("teacher", event.target.value)}/></label><label className="field"><span>地点</span><input value={form.classroom} onChange={(event) => set("classroom", event.target.value)}/></label><label className="field"><span>星期</span><select value={form.weekday} onChange={(event) => set("weekday", Number(event.target.value))}>{[1,2,3,4,5,6,7].map((day) => <option key={day} value={day}>周{["一","二","三","四","五","六","日"][day - 1]}</option>)}</select></label><label className="field"><span>节次</span><div className="inline-fields"><input type="number" min={1} max={20} value={form.startSection} onChange={(event) => set("startSection", Number(event.target.value))}/><span>至</span><input type="number" min={1} max={20} value={form.endSection} onChange={(event) => set("endSection", Number(event.target.value))}/></div></label><label className="field"><span>开始时间（可选）</span><input type="time" value={form.startTime} onChange={(event) => set("startTime", event.target.value)}/></label><label className="field"><span>结束时间（可选）</span><input type="time" value={form.endTime} onChange={(event) => set("endTime", event.target.value)}/></label><label className="field"><span>原课程周次</span><input disabled value={`第 ${course.startWeek}-${course.endWeek} 周`}/></label><label className="field"><span>课程颜色</span><input type="color" value={form.color} onChange={(event) => set("color", event.target.value)}/></label></div><fieldset className="scope-picker"><legend>本次修改应用到</legend><label><input type="radio" checked={scope === "all"} onChange={() => setScope("all")}/> 全部周次（第 {course.startWeek}-{course.endWeek} 周）</label><label><input type="radio" checked={scope === "some"} onChange={() => setScope("some")}/> 只改某几周</label>{scope === "some" && <input autoFocus value={weeks} onChange={(event) => setWeeks(event.target.value)} placeholder="例如：1,3-5"/>}</fieldset>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><span className="spacer"/><button type="button" className="ghost" onClick={onClose}>取消</button><button className="primary" disabled={saving || !form.name.trim()}>{saving ? "保存中…" : "保存修改"}</button></div></form></div></div>;
}

function ScheduleEditDialog({ schedule, onClose, onSave }: { schedule: Schedule; onClose: () => void; onSave: (input: ScheduleUpdateInput) => Promise<void> }) {
  const [name, setName] = useState(schedule.name), [date, setDate] = useState(schedule.semesterStartDate), [color, setColor] = useState(schedule.color), [saving, setSaving] = useState(false);
  return <div className="modal-backdrop"><div className="modal"><form onSubmit={async (event) => { event.preventDefault(); setSaving(true); try { await onSave({ name, semesterStartDate: date, color, routines: schedule.routines }); } finally { setSaving(false); } }}><div className="modal-header"><div><span className="section-kicker">EDIT SCHEDULE</span><h2>编辑课表</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><div className="form-grid"><label className="field full"><span>课表名称 *</span><input autoFocus maxLength={60} value={name} onChange={(event) => setName(event.target.value)}/></label><label className="field"><span>开学日期</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)}/></label><label className="field"><span>课表颜色</span><input type="color" value={color} onChange={(event) => setColor(event.target.value)}/></label></div><div className="modal-actions"><span className="spacer"/><button type="button" className="ghost" onClick={onClose}>取消</button><button className="primary" disabled={saving || !name.trim() || !date}>{saving ? "保存中…" : "保存课表"}</button></div></form></div></div>;
}

function RoutineDialog({ schedule, onClose, onSave }: { schedule: Schedule; onClose: () => void; onSave: (input: ScheduleUpdateInput) => Promise<void> }) {
  const [content, setContent] = useState(schedule.routines.length ? JSON.stringify({ schemaVersion: 1, routines: schedule.routines }, null, 2) : ""), [error, setError] = useState(""), [copied, setCopied] = useState(false), [saving, setSaving] = useState(false);
  const submit = async () => { try { const routines = parseRoutineImport(content); setSaving(true); await onSave({ name: schedule.name, semesterStartDate: schedule.semesterStartDate, color: schedule.color, routines }); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setSaving(false); } };
  return <div className="modal-backdrop"><div className="modal import-modal"><div className="modal-header"><div><span className="section-kicker">DAILY ROUTINE</span><h2>添加作息</h2></div><button className="close" onClick={onClose}>×</button></div><p className="field-help">作息默认为空。设置后会显示在课表每个节次左边，并可让 AI 按模板识别或生成。</p><div className="template-box"><div><strong>AI 作息提示词</strong><p>复制后把学校作息图片或文字一起发给 AI。</p></div><button className="ghost" onClick={async () => { await navigator.clipboard.writeText(routineAiPrompt); setCopied(true); }}>{copied ? "已复制" : "复制提示词"}</button></div><textarea className="json-input" rows={10} value={content} onChange={(event) => setContent(event.target.value)} placeholder={routineTemplate}/>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><span className="spacer"/><button className="ghost" onClick={onClose}>取消</button><button className="primary" disabled={!content.trim() || saving} onClick={() => void submit()}>{saving ? "保存中…" : "保存作息"}</button></div></div></div>;
}

function ImportScheduleDialog({ schedules, onClose, onImport }: { schedules: Schedule[]; onClose: () => void; onImport: (input: ScheduleImportInput) => Promise<void> }) {
  const [content, setContent] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false), [copied, setCopied] = useState(false);
  const [target, setTarget] = useState("new"), [name, setName] = useState("新课表"), [startDate, setStartDate] = useState("2026-09-01"), [color, setColor] = useState("#6f8f7b"), [mode, setMode] = useState<"append" | "replace">("append");
  useEffect(() => { const schedule = schedules.find((item) => item.id === target); if (schedule) { setName(schedule.name); setStartDate(schedule.semesterStartDate); setColor(schedule.color); } }, [target, schedules]);
  const submit = async () => { try { const courses = parseScheduleImport(content); setSaving(true); await onImport({ scheduleId: target === "new" ? null : target, scheduleName: name, semesterStartDate: startDate, color, mode, courses }); } catch (reason) { setError(reason instanceof Error ? reason.message : "导入失败"); } finally { setSaving(false); } };
  const chooseFile = async (file?: File) => { if (!file) return; try { setContent(await file.text()); setError(""); } catch { setError("无法读取这个文件"); } };
  return <div className="modal-backdrop"><div className="modal import-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="section-kicker">IMPORT SCHEDULE</span><h2>单独导入课表</h2></div><button className="close" onClick={onClose}>×</button></div><div className="import-steps"><span>1. 把课表图片或 PDF 发给 AI</span><span>2. 要求 AI 严格按模板返回 JSON</span><span>3. 在这里导入结果</span></div>
    <div className="template-box"><div><strong>AI 识别模板</strong><p>复制后连同课表文件一起发给 AI。</p></div><button className="ghost" onClick={async () => { await navigator.clipboard.writeText(scheduleTemplate); setCopied(true); }}>{copied ? "已复制" : "复制模板"}</button></div>
    <div className="form-grid"><label className="field"><span>导入到</span><select value={target} onChange={(event) => setTarget(event.target.value)}><option value="new">新增课表</option>{schedules.map((schedule) => <option value={schedule.id} key={schedule.id}>{schedule.name}</option>)}</select></label><label className="field"><span>方式</span><select value={mode} disabled={target === "new"} onChange={(event) => setMode(event.target.value as "append" | "replace")}><option value="append">添加到原课表</option><option value="replace">覆盖原课表</option></select></label><label className="field"><span>课表名称</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>开学日期</span><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label className="field"><span>课表颜色</span><input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label></div><label className="file-drop">选择 AI 返回的 JSON 文件<input type="file" accept="application/json,.json" onChange={(event) => void chooseFile(event.target.files?.[0])}/></label><div className="or">或者直接粘贴 JSON</div><textarea className="json-input" rows={10} value={content} onChange={(event) => setContent(event.target.value)} placeholder={scheduleTemplate}/>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><span className="spacer"/><button className="ghost" onClick={onClose}>取消</button><button className="primary" disabled={!content.trim() || saving || !name.trim() || !startDate} onClick={() => void submit()}>{saving ? "导入中…" : "确认导入"}</button></div></div></div>;
}

function TaskDialog({ task, courses, initialDueAt, initialCourseId, onClose, onSave, onDelete }: { task: Task | null; courses: Course[]; initialDueAt?: string; initialCourseId?: string; onClose: () => void; onSave: (input: TaskInput) => Promise<void>; onDelete: (task: Task) => Promise<void> }) {
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<TaskInput>(() => task ? { title: task.title, taskType: task.taskType, description: task.description, tags: task.tags, priority: task.priority, startAt: task.startAt, dueAt: task.dueAt, reminderAt: task.reminderAt, notes: task.notes, courseId: task.courseId, courseTaskType: task.courseTaskType, customCourseTaskType: task.customCourseTaskType } : initialCourseId ? { ...createCourseTaskDraft(initialCourseId), dueAt: initialDueAt ?? null } : { title: "", taskType: "other", description: "", tags: [], priority: "medium", startAt: null, dueAt: initialDueAt ?? null, reminderAt: null, notes: "", courseId: null, courseTaskType: null, customCourseTaskType: null });
  const set = <K extends keyof TaskInput>(key: K, value: TaskInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim()) return; setSaving(true); try { await onSave({ ...form, title: form.title.trim(), priority: form.taskType === "course" ? "medium" : form.priority, notes: form.taskType === "course" ? "" : form.notes }); } finally { setSaving(false); } };
  const isCourse = form.taskType === "course";
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal" role="dialog" aria-modal="true"><form onSubmit={submit}><div className="modal-header"><div><span className="section-kicker">{isCourse ? "COURSE TASK" : task ? "EDIT TASK" : "NEW TASK"}</span><h2>{isCourse ? (task ? "编辑课程任务" : "新增课程任务") : task ? "编辑任务" : "新增任务"}</h2></div><button type="button" className="close" onClick={onClose}>×</button></div>
    <label className="field full"><span>任务名称 *</span><input autoFocus maxLength={120} value={form.title} onChange={(event) => set("title", event.target.value)} placeholder={isCourse ? "例如：完成第三章习题" : "例如：准备竞赛报名材料"} /></label><div className="form-grid">{!isCourse && <><label className="field"><span>类型</span><select value={form.taskType} onChange={(event) => { const taskType = event.target.value as TaskType; setForm((current) => ({ ...current, taskType, courseId: taskType === "course" ? current.courseId : null, courseTaskType: taskType === "course" ? "assignment" : null })); }}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>优先级</span><select value={form.priority} onChange={(event) => set("priority", event.target.value as TaskPriority)}>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></>}
      {isCourse && <><label className="field"><span>课程 *</span><select value={form.courseId ?? ""} onChange={(event) => set("courseId", event.target.value || null)}><option value="">请选择已导入课程</option>{courses.map((course) => <option key={course.recordId} value={course.recordId}>{course.name} · 周{course.weekday} 第{course.startSection}-{course.endSection}节</option>)}</select></label><label className="field"><span>任务类型 *</span><select value={form.courseTaskType ?? "assignment"} onChange={(event) => set("courseTaskType", event.target.value as TaskInput["courseTaskType"])}>{Object.entries(courseTaskLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label>{form.courseTaskType === "other" && <label className="field full"><span>新的类型名称（可选）</span><input maxLength={40} value={form.customCourseTaskType ?? ""} onChange={(event) => set("customCourseTaskType", event.target.value || null)} placeholder="例如：课堂展示"/></label>}</>}
      <label className="field"><span>开始时间</span><input type="datetime-local" value={form.startAt ?? ""} onChange={(event) => set("startAt", event.target.value || null)} /></label><label className="field"><span>截止时间</span><input type="datetime-local" value={form.dueAt ?? ""} onChange={(event) => set("dueAt", event.target.value || null)} /></label>{!isCourse && <label className="field full"><span>标签（用逗号分隔）</span><input value={form.tags.join(", ")} onChange={(event) => set("tags", event.target.value.split(/[,，]/).map((value) => value.trim()).filter(Boolean))} placeholder="每日练习, 重要" /></label>}<label className="field full"><span>{isCourse ? "任务描述 / 备注" : "任务描述"}</span><textarea rows={4} value={form.description} onChange={(event) => set("description", event.target.value)} placeholder="补充具体内容和完成标准" /></label>{!isCourse && <label className="field full"><span>备注</span><textarea rows={2} value={form.notes} onChange={(event) => set("notes", event.target.value)} /></label>}</div>
    <div className="modal-actions">{task && <button type="button" className="danger" onClick={() => onDelete(task)}>删除任务</button>}<span className="spacer"/><button type="button" className="ghost" onClick={onClose}>取消</button><button className="primary" disabled={saving || !form.title.trim() || (form.taskType === "course" && !form.courseId)}>{saving ? "保存中…" : "保存任务"}</button></div></form></div></div>;
}

function Shell() {
  const [tasks, setTasks] = useState<Task[]>([]), [courses, setCourses] = useState<Course[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [ieltsCourses, setIeltsCourses] = useState<IeltsCourse[]>([]);
  const [ieltsWorkCount, setIeltsWorkCount] = useState(0);
  const [scheduleSettings, setScheduleSettings] = useState<ScheduleSettings>({ semesterStartDate: "" });
  const [dialog, setDialog] = useState<{ task: Task | null; dueAt?: string; courseId?: string } | null>(null);
  const [importOpen, setImportOpen] = useState(false);
  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    const [taskResult, courseResult, settingsResult, scheduleResult, ieltsResult] = await Promise.allSettled([
      taskApi.list(), courseApi.list(), courseApi.getSettings(), courseApi.listSchedules(), ieltsApi.get(),
    ]);
    const failures: string[] = [];
    const explainFailure = (module: string, reason: unknown) => failures.push(`${module}读取失败：${reason instanceof Error ? reason.message : String(reason)}`);
    if (taskResult.status === "fulfilled") setTasks(taskResult.value);
    else explainFailure("任务", taskResult.reason);
    if (courseResult.status === "fulfilled") setCourses(courseResult.value);
    else explainFailure("课表", courseResult.reason);
    if (settingsResult.status === "fulfilled") setScheduleSettings(settingsResult.value);
    else explainFailure("课表设置", settingsResult.reason);
    if (scheduleResult.status === "fulfilled") setSchedules(scheduleResult.value);
    else explainFailure("课表列表", scheduleResult.reason);
    if (ieltsResult.status === "fulfilled") {
      setIeltsCourses(ieltsResult.value.courses);
      setIeltsWorkCount(ieltsResult.value.works.length);
      failures.push(...ieltsResult.value.readWarnings);
    } else explainFailure("雅思", ieltsResult.reason);
    setError(failures.join("；"));
    setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  const add = (dueAt?: string) => setDialog({ task: null, dueAt });
  const save = async (input: TaskInput) => { try { if (dialog?.task) await taskApi.update(dialog.task.recordId, input); else await taskApi.create(input); setDialog(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } };
  const setStatus = async (task: Task, status: TaskStatus) => { try { const updated = await taskApi.setStatus(task.recordId, status); setTasks((items) => items.map((item) => item.recordId === updated.recordId ? updated : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : "更新失败"); } };
  const remove = async (task: Task) => { if (!window.confirm(`确定删除“${task.title}”吗？记录会保留为可恢复的软删除状态。`)) return; try { await taskApi.remove(task.recordId); setDialog(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除失败"); } };
  const importSchedule = async (input: ScheduleImportInput) => { const imported = await courseApi.importSchedule(input); setCourses(imported); setSchedules(await courseApi.listSchedules()); setImportOpen(false); };
  const deleteSchedule = async (id: string) => { try { await courseApi.deleteSchedule(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除课表失败"); } };
  const updateCourse = async (id: string, input: CourseUpdateInput) => { try { setCourses(await courseApi.updateCourse(id, input)); } catch (reason) { setError(reason instanceof Error ? reason.message : "修改课程失败"); throw reason; } };
  const updateSchedule = async (id: string, input: ScheduleUpdateInput) => { try { await courseApi.updateSchedule(id, input); setSchedules(await courseApi.listSchedules()); } catch (reason) { setError(reason instanceof Error ? reason.message : "修改课表失败"); throw reason; } };
  const pageProps = { tasks, courses, schedules, ieltsCourses, ieltsWorkCount, semesterStartDate: scheduleSettings.semesterStartDate, onAdd: add, onEdit: (task: Task) => setDialog({ task }), onStatus: setStatus };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">近</div><div><strong>近期规划</strong><small>Recent Plan</small></div></div><nav><NavLink to="/" end><Icon name="home"/><span>总览</span></NavLink><NavLink to="/tasks"><Icon name="tasks"/><span>全部任务</span></NavLink><NavLink to="/calendar"><Icon name="calendar"/><span>日历</span></NavLink><NavLink to="/courses"><Icon name="course"/><span>课程与课表</span></NavLink><NavLink to="/ielts"><span className="nav-letter">I</span><span>雅思</span></NavLink></nav><div className="sidebar-foot"><span className="local-dot"/>本地离线保存</div></aside><main className="content">{error && <div className="error-banner"><span>{error}</span><button onClick={() => setError("")}>×</button></div>}{loading ? <div className="loading"><span/>正在读取本地规划…</div> : <Routes><Route path="/" element={<Dashboard {...pageProps}/>} /><Route path="/tasks" element={<TasksPage {...pageProps}/>} /><Route path="/calendar" element={<CalendarPage {...pageProps}/>} /><Route path="/courses" element={<CoursePage courses={courses} schedules={schedules} tasks={tasks} onDeleteSchedule={deleteSchedule} onSaveCourse={updateCourse} onSaveSchedule={updateSchedule} onOpenImport={() => setImportOpen(true)} onAddAssignment={(courseId) => setDialog({ task: null, courseId })} onEditTask={(task) => setDialog({ task })}/>} /><Route path="/ielts/*" element={<IeltsPage onCoursesChange={setIeltsCourses}/>}/></Routes>}</main>{dialog && <TaskDialog task={dialog.task} courses={courses} initialDueAt={dialog.dueAt} initialCourseId={dialog.courseId} onClose={() => setDialog(null)} onSave={save} onDelete={remove}/>} {importOpen && <ImportScheduleDialog schedules={schedules} onClose={() => setImportOpen(false)} onImport={importSchedule}/>}</div>;
}

export default function App() { return <BrowserRouter><Shell/></BrowserRouter>; }
