import { useEffect, useMemo, useState } from "react";
import { NavLink, Route, Routes } from "react-router-dom";
import { autoIeltsBandScore, buildIeltsCompletion, filterWorks, ieltsCourseTemplate, latestMock, overallBandScore, parseIeltsCourseImport, recentCategoryAverages, sortCompletedWorks, sortIeltsCourses, splitWorksByTrash, workResultSummary, workTimeProgress } from "./domain/ielts";
import { ieltsApi } from "./services/ieltsApi";
import type { IeltsCategory, IeltsData, IeltsMock, IeltsScores, IeltsWork } from "./types/ielts";
import "./Ielts.css";
import "./IeltsCourse.css";

const labels: Record<IeltsCategory, string> = { reading: "阅读", listening: "听力", writing: "写作", speaking: "口语" };
const emptyData: IeltsData = { goal: null, works: [], mocks: [], courses: [], readWarnings: [] };
const nowLocal = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };

function ScoreRing({ label, score, target }: { label: string; score: number | null; target?: number }) {
  const value = score ?? 0;
  return <div className="score-card"><div className="score-ring" style={{ "--score": `${value / 9 * 360}deg` } as React.CSSProperties}><div><strong>{score ?? "—"}</strong><small>/ 9</small></div></div><b>{label}</b>{target != null && <span>目标 {target}</span>}</div>;
}

function GoalPage({ data, refresh }: { data: IeltsData; refresh: () => Promise<void> }) {
  const recent = latestMock(data.mocks), averages = recentCategoryAverages(data.works);
  const averageScores = Object.values(averages).every((score) => score != null) ? averages as IeltsScores : null;
  const [editing, setEditing] = useState(false), [form, setForm] = useState<IeltsScores>(data.goal ?? { reading: 7, listening: 7, writing: 6.5, speaking: 6.5 });
  const save = async () => { await ieltsApi.saveGoal(form); setEditing(false); await refresh(); };
  return <><div className="ielts-heading"><div><span>GOAL OVERVIEW</span><h2>目标汇总</h2></div><button className="ghost" onClick={() => setEditing(!editing)}>{editing ? "取消" : "设置目标"}</button></div>{editing && <div className="panel score-form">{Object.entries(labels).map(([key,label]) => <label key={key}>{label}<input type="number" min="0" max="9" step="0.5" value={form[key as IeltsCategory]} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })}/></label>)}<button className="primary" onClick={() => void save()}>保存目标</button></div>}
    <h3 className="metric-title">最近一次模考</h3><div className="score-grid">{Object.entries(labels).map(([key,label]) => <ScoreRing key={key} label={label} score={recent?.[key as IeltsCategory] ?? null} target={data.goal?.[key as IeltsCategory]}/>)}<ScoreRing label="总分" score={recent ? overallBandScore(recent) : null} target={data.goal ? overallBandScore(data.goal) : undefined}/></div>
    <h3 className="metric-title">近期作业平均 · 每科最近 5 次</h3><div className="score-grid compact">{Object.entries(labels).map(([key,label]) => <ScoreRing key={key} label={label} score={averages[key as IeltsCategory]} target={data.goal?.[key as IeltsCategory]}/>)}<ScoreRing label="总分" score={averageScores ? overallBandScore(averageScores) : null} target={data.goal ? overallBandScore(data.goal) : undefined}/></div></>;
}

function WorkCircle({ work, onComplete, onEdit, onDelete }: { work: IeltsWork; onComplete?: (work: IeltsWork) => void; onEdit?: (work: IeltsWork) => void; onDelete?: (work: IeltsWork) => void }) {
  const summary = workResultSummary(work);
  const hasQuestionBreakdown = Boolean(work.readingCorrect?.length || work.listeningCorrect?.length);
  return <article className="work-card-wrap"><button data-category={work.category} className={`work-orbit ${work.completedAt ? "completed" : ""}`} onClick={() => onComplete?.(work)}><span className="orbit-date">截止 {work.dueAt?.replace("T", " ") ?? "未设置"}</span><span className="work-double-ring" style={{ "--time-progress": `${workTimeProgress(work)}deg` } as React.CSSProperties}><span className="work-circle"><strong>{work.name}</strong><small>{labels[work.category]}</small>{work.completedAt && <b className={hasQuestionBreakdown ? "question-summary" : ""}>{summary}</b>}<span className="work-time"><em>应使用 {work.expectedMinutes ?? "—"} 分钟</em><em>实际 {work.actualMinutes ?? "—"} 分钟</em></span></span></span></button>{work.completedAt && (onEdit || onDelete) && <div className="work-actions">{onEdit&&<button onClick={()=>onEdit(work)}>修改</button>}{onDelete&&<button className="danger-link" onClick={()=>onDelete(work)}>删除</button>}</div>}</article>;
}

function HomeworkPage({ data, refresh }: { data: IeltsData; refresh: () => Promise<void> }) {
  const [adding, setAdding] = useState(false), [completing, setCompleting] = useState<IeltsWork | null>(null);
  const [category, setCategory] = useState<IeltsCategory | "all">("all");
  const [editingResult, setEditingResult] = useState(false), [trashOpen, setTrashOpen] = useState(false);
  const [form, setForm] = useState({ name: "", category: "reading" as IeltsCategory, dueAt: "", expectedMinutes: 60 });
  const [result, setResult] = useState<{ actualMinutes: number; score: number; parts: Array<number | null>; readingTotals: number[]; listeningTotals: number[] }>({ actualMinutes: 60, score: 6.5, parts: [null,null,null,null], readingTotals: [13,13,14], listeningTotals: [10,10,10,10] });
  const [completionError, setCompletionError] = useState("");
  const split = splitWorksByTrash(data.works);
  const pending = filterWorks(split.active.filter((work) => !work.completedAt), category);
  const completed = filterWorks(sortCompletedWorks(split.active), category);
  const add = async () => { await ieltsApi.createWork({ ...form, dueAt: form.dueAt || null, expectedMinutes: form.expectedMinutes || null }); setAdding(false); await refresh(); };
  const beginComplete = (work: IeltsWork) => { setEditingResult(false); setCompleting(work); setResult({ actualMinutes: 60, score: 6.5, parts: [null,null,null,null], readingTotals: [13,13,14], listeningTotals: [10,10,10,10] }); setCompletionError(""); };
  const beginEdit = (work: IeltsWork) => { const savedParts = work.category === "reading" ? work.readingCorrect : work.listeningCorrect; setEditingResult(true); setCompleting(work); setResult({ actualMinutes: work.actualMinutes ?? 60, score: work.score ?? 6.5, parts: [...(savedParts ?? []), null, null, null, null].slice(0,4), readingTotals: [13,13,14].map((fallback,index)=>work.readingTotals?.[index] ?? fallback), listeningTotals: [10,10,10,10].map((fallback,index)=>work.listeningTotals?.[index] ?? fallback) }); setCompletionError(""); };
  const partCount = result.parts.slice(0, completing?.category === "reading" ? 3 : 4).filter((value) => value != null).length;
  const needsManualScore = completing ? ["writing", "speaking"].includes(completing.category) : false;
  const partLimit = completing?.category === "reading" ? 3 : 4;
  const activeTotals = completing?.category === "reading" ? result.readingTotals : result.listeningTotals;
  const automaticScore = completing && (completing.category === "reading" || completing.category === "listening") && partCount === partLimit && result.parts.slice(0, partLimit).every((value, index) => value != null && value >= 0 && value <= activeTotals[index] && activeTotals[index] > 0)
    ? autoIeltsBandScore(completing.category, result.parts.slice(0, partLimit).reduce<number>((sum, value) => sum + (value ?? 0), 0), activeTotals.slice(0, partLimit).reduce((sum, value) => sum + value, 0)) : null;
  const complete = async () => { if (!completing) return; try { const totals = completing.category === "reading" ? result.readingTotals : result.listeningTotals; const input = buildIeltsCompletion(completing.category, result.actualMinutes, needsManualScore ? result.score : null, result.parts, totals); if (editingResult) await ieltsApi.updateWorkResult(completing.recordId, input); else await ieltsApi.completeWork(completing.recordId, input); setCompleting(null); await refresh(); } catch (reason) { setCompletionError(reason instanceof Error ? reason.message : "完成记录不正确"); } };
  const removeWork = async (work: IeltsWork) => { if (!window.confirm(`确定把“${work.name}”移到垃圾箱吗？之后可以恢复。`)) return; await ieltsApi.deleteWork(work.recordId); await refresh(); };
  const restoreWork = async (work: IeltsWork) => { await ieltsApi.restoreWork(work.recordId); await refresh(); };
  return <><div className="ielts-heading"><div><span>HOMEWORK & PRACTICE</span><h2>作业与自测</h2></div><button className="primary" onClick={() => setAdding(true)}>＋ 添加作业</button></div><div className="category-filters"><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>全部</button>{Object.entries(labels).map(([key,label])=><button data-category={key} className={category === key ? "active" : ""} onClick={() => setCategory(key as IeltsCategory)} key={key}>{label}</button>)}</div><h3 className="work-section-title">未完成</h3><div className="work-grid">{pending.length ? pending.map((work) => <WorkCircle key={work.recordId} work={work} onComplete={beginComplete}/>) : <p className="ielts-empty">暂无待完成作业</p>}</div><div className="completed-heading"><h3 className="work-section-title completed-title">已完成</h3><button className="ghost" onClick={()=>setTrashOpen(!trashOpen)}>垃圾箱（{split.trash.length}）</button></div><div className="work-grid">{completed.length ? completed.map((work) => <WorkCircle key={work.recordId} work={work} onEdit={beginEdit} onDelete={(item)=>void removeWork(item)}/>) : <p className="ielts-empty">还没有完成记录</p>}</div>{trashOpen&&<section className="trash-panel panel"><h3>垃圾箱</h3>{split.trash.length ? split.trash.map(work=><div className="trash-row" key={work.recordId}><div><strong>{work.name}</strong><span>{labels[work.category]} · 删除于 {work.deletedAt?.replace("T"," ").slice(0,16)}</span></div><button className="ghost" onClick={()=>void restoreWork(work)}>恢复</button></div>) : <p className="inline-empty">垃圾箱为空</p>}</section>}
    {adding && <div className="ielts-dialog panel"><h3>新增雅思作业</h3><label>名称<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>科目<select value={form.category} onChange={(e)=>setForm({...form,category:e.target.value as IeltsCategory})}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>截止时间<input type="datetime-local" value={form.dueAt} onChange={(e)=>setForm({...form,dueAt:e.target.value})}/></label><label>预计完成时间（分钟）<input type="number" value={form.expectedMinutes} onChange={(e)=>setForm({...form,expectedMinutes:Number(e.target.value)})}/></label><div><button className="ghost" onClick={()=>setAdding(false)}>取消</button><button className="primary" disabled={!form.name.trim()} onClick={()=>void add()}>保存</button></div></div>}
    {completing && <div className="ielts-dialog panel"><h3>{editingResult ? "修改" : "完成"}「{completing.name}」</h3><label>完成时间（分钟）<input type="number" min="1" value={result.actualMinutes} onChange={(e)=>setResult({...result,actualMinutes:Number(e.target.value)})}/></label>{needsManualScore && <label>本次分数（0–9）<input type="number" min="0" max="9" step="0.5" value={result.score} onChange={(e)=>setResult({...result,score:Number(e.target.value)})}/></label>}{completing.category === "reading" && <div className="part-entry-list"><span>可填写 1–3 篇；全部完成后按实际总题数自动换算分数</span>{[0,1,2].map(i=><div className="part-entry" key={i}><b>第 {i+1} 篇</b><label>总题数<input type="number" min="1" max="15" value={result.readingTotals[i]} onChange={(e)=>{const readingTotals=[...result.readingTotals];readingTotals[i]=Number(e.target.value);setResult({...result,readingTotals})}}/></label><label>答对题数<input type="number" min="0" max="15" placeholder="未做留空" value={result.parts[i] ?? ""} onChange={(e)=>{const parts=[...result.parts];parts[i]=e.target.value === "" ? null : Number(e.target.value);setResult({...result,parts})}}/></label></div>)}</div>}{completing.category === "listening" && <div className="part-entry-list"><span>可填写 1–4 个部分；全部完成后按实际总题数自动换算分数</span>{[0,1,2,3].map(i=><div className="part-entry" key={i}><b>Part {i+1}</b><label>总题数<input type="number" min="1" max="10" value={result.listeningTotals[i]} onChange={(e)=>{const listeningTotals=[...result.listeningTotals];listeningTotals[i]=Number(e.target.value);setResult({...result,listeningTotals})}}/></label><label>答对题数<input type="number" min="0" max="10" placeholder="未做留空" value={result.parts[i] ?? ""} onChange={(e)=>{const parts=[...result.parts];parts[i]=e.target.value === "" ? null : Number(e.target.value);setResult({...result,parts})}}/></label></div>)}</div>}{automaticScore != null && <p className="completion-score-preview">自动换算分数：<strong>{automaticScore}</strong> 分</p>}{completionError&&<p className="form-error">{completionError}</p>}<div><button className="ghost" onClick={()=>setCompleting(null)}>取消</button><button className="primary" onClick={()=>void complete()}>{editingResult ? "保存修改" : "确认完成"}</button></div></div>}
  </>;
}

function IeltsCoursesPage({ data, refresh, onCoursesChange }: { data: IeltsData; refresh: () => Promise<void>; onCoursesChange: (courses: IeltsData["courses"]) => void }) {
  const [importing, setImporting] = useState(false), [content, setContent] = useState(""), [error, setError] = useState(""), [copied, setCopied] = useState(false);
  const courses = sortIeltsCourses(data.courses);
  const chooseFile = async (file?: File) => { if (file) setContent(await file.text()); };
  const submit = async () => { try { const imported = await ieltsApi.importCourses(parseIeltsCourseImport(content)); onCoursesChange(imported); setImporting(false); setContent(""); setError(""); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "导入失败"); } };
  return <><div className="ielts-heading"><div><span>IELTS COURSES</span><h2>课程</h2></div><button className="primary" onClick={() => setImporting(true)}>＋ 导入课程</button></div><div className="ielts-course-timeline">{courses.length ? courses.map((course) => <article className="panel ielts-course-row" style={{ borderLeft: `4px solid ${course.color}` }} key={course.recordId}><time><strong>{course.startAt.slice(5,10)}</strong><span>{course.startAt.slice(11,16)}–{course.endAt.slice(11,16)}</span></time><i/><div><strong>{course.name}</strong><span>{course.teacher || "教师未填写"}{course.classroom ? ` · ${course.classroom}` : ""}</span>{course.notes && <small>{course.notes}</small>}</div></article>) : <p className="ielts-empty">还没有雅思课程，请使用 AI 模板导入。</p>}</div>{importing && <div className="ielts-dialog panel ielts-course-import"><h3>导入雅思课程</h3><div className="template-box"><div><strong>AI 导入模板</strong><p>复制模板后连同课程安排图片发给 AI。</p></div><button className="ghost" onClick={async()=>{await navigator.clipboard.writeText(ieltsCourseTemplate);setCopied(true)}}>{copied ? "已复制" : "复制模板"}</button></div><label className="file-drop">选择 AI 返回的 JSON 文件<input type="file" accept="application/json,.json" onChange={event=>void chooseFile(event.target.files?.[0])}/></label><div className="or">或者直接粘贴 AI 的完整回复</div><textarea className="json-input" rows={9} value={content} onChange={event=>setContent(event.target.value)} placeholder={ieltsCourseTemplate}/>{error&&<p className="form-error">{error}</p>}<div><button className="ghost" onClick={()=>setImporting(false)}>取消</button><button className="primary" disabled={!content.trim()} onClick={()=>void submit()}>确认导入</button></div></div>}</>;
}

function MockPage({ data, refresh }: { data: IeltsData; refresh: () => Promise<void> }) {
  const [form,setForm]=useState<Omit<IeltsMock,"recordId"|"createdAt"|"updatedAt">>({examAt:nowLocal(),reading:6.5,listening:6.5,writing:6,speaking:6,notes:""});
  const save=async()=>{await ieltsApi.createMock(form);await refresh()};
  return <><div className="ielts-heading"><div><span>MOCK EXAMS</span><h2>手动模考</h2></div></div><section className="panel mock-form"><label>模考时间<input type="datetime-local" value={form.examAt} onChange={e=>setForm({...form,examAt:e.target.value})}/></label>{Object.entries(labels).map(([key,label])=><label key={key}>{label}分数<input type="number" min="0" max="9" step="0.5" value={form[key as IeltsCategory]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}<label className="mock-notes">备注<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" onClick={()=>void save()}>保存模考</button></section><h3 className="metric-title">历史模考</h3><div className="mock-history">{[...data.mocks].sort((a,b)=>b.examAt.localeCompare(a.examAt)).map(mock=><div className="panel mock-row" key={mock.recordId}><strong>{mock.examAt.replace("T"," ")}</strong>{Object.entries(labels).map(([key,label])=><span key={key}>{label} {mock[key as IeltsCategory]}</span>)}</div>)}</div></>;
}

export default function IeltsPage({ onCoursesChange = () => {} }: { onCoursesChange?: (courses: IeltsData["courses"]) => void }) {
  const [data,setData]=useState<IeltsData>(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const refresh=async()=>{try{setData(await ieltsApi.get());setError("")}catch(reason){setError(reason instanceof Error?reason.message:"读取雅思数据失败")}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[]);
  const props=useMemo(()=>({data,refresh}),[data]);
  return <div className="page ielts-page"><header className="page-header"><div><p className="eyebrow">IELTS</p><h1>雅思</h1><p>目标、作业、课程和模考成绩。</p></div></header><div className="ielts-workspace"><nav className="ielts-tabs"><NavLink to="/ielts" end>目标</NavLink><NavLink to="/ielts/homework">作业与自测</NavLink><NavLink to="/ielts/courses">课程</NavLink><NavLink to="/ielts/mocks">历史模考成绩</NavLink></nav><section className="ielts-content">{error&&<p className="form-error">{error}</p>}{data.readWarnings.map(warning=><p className="form-error" key={warning}>{warning}。其他记录已加载，请检查本地文件。</p>)}{loading?<p className="ielts-empty">正在读取…</p>:<Routes><Route index element={<GoalPage {...props}/>} /><Route path="homework" element={<HomeworkPage {...props}/>} /><Route path="courses" element={<IeltsCoursesPage {...props} onCoursesChange={onCoursesChange}/>} /><Route path="mocks" element={<MockPage {...props}/>} /></Routes>}</section></div></div>;
}
